const
	$blockTime = document.querySelector('[data-block-time]'),
	$title = document.querySelector('[data-title]'),
	$count = document.querySelector('[data-count]'),
	$add = document.querySelector('[data-add]'),
	$hamburguer = document.querySelector('[data-hamburguer]'),
	$menu = document.querySelector('[data-menu]'),
	$displayDatetime = document.querySelector('[data-display-datetime]'),
	$datetime = document.querySelector('[data-datetime]'),
	$date = document.querySelector('[data-date]'),
	$time = document.querySelector('[data-time]'),
	$resetCount = document.querySelector('[data-reset-count]'),
	$logs = document.querySelector('[data-logs]'),
	$modal = document.querySelector('[data-modal]'),
	$modalConfirm = document.querySelector('[data-modal-confirm]');
